[workspace]
members = ["crates/rtsan", "crates/rtsan-sys", "example"]
resolver = "2"

[workspace.dependencies]
rtsan = { path = "crates/rtsan" }
rtsan-macros = { path = "crates/rtsan-macros" }
rtsan-sys = { path = "crates/rtsan-sys" }
