[workspace]
resolver = "2"
members = ["crates/rtsan-sys", "examples/integration-example"]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.77"
authors = ["Stephan Eckes <stephan@neodsp.com>"]
license = "Apache-2.0"
repository = "https://github.com/realtime-sanitizer/rtsan-standalone-rs"
readme = "README.md"

[workspace.dependencies]
rtsan = { path = "." }
rtsan-macros = { path = "crates/rtsan-macros" }
rtsan-sys = { path = "crates/rtsan-sys" }

[package]
name = "rtsan"
description = "A Rust wrapper for RTSan standalone"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
rtsan-macros = { workspace = true }

[target.'cfg(any(target_os = "macos", target_os = "linux"))'.dependencies]
rtsan-sys = { workspace = true, optional = true }

[dev-dependencies]
criterion = "0.5.1"

[features]
enable = ["rtsan-macros/enable", "rtsan-sys"]

[[bench]]
name = "rtsan-bench"
harness = false
