[workspace]
members = ["rtsan-sys"]

[package]
name = "rtsan"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
rtsan-macros = { path = "rtsan-macros" }
rtsan-sys = { path = "rtsan-sys" }
