[package]
name = "rtsan-standalone-sys"
description = "Unsafe Rust bindings for RTSan standalone library"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]

[build-dependencies]
tempfile = "3"
num_cpus = "1.16"
