/* automatically generated by rust-bindgen 0.70.1 */

extern "C" {
    pub fn __rtsan_realtime_enter();
}
extern "C" {
    pub fn __rtsan_realtime_exit();
}
extern "C" {
    pub fn __rtsan_disable();
}
extern "C" {
    pub fn __rtsan_enable();
}
extern "C" {
    pub fn __rtsan_ensure_initialized();
}
extern "C" {
    pub fn __rtsan_notify_blocking_call(blocking_function_name: *const ::std::os::raw::c_char);
}
