[package]
name = "rtsan-sys"
description = "Unsafe Rust bindings for rtsan standalone library"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]

[build-dependencies]
tempfile = "3.14"
