name: 🚫 No-Std Support

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  nostd:
    runs-on: ubuntu-latest
    name: 🔌 ARM Cortex-M Check
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: rustup target add thumbv7m-none-eabi
      - run: cargo check --target thumbv7m-none-eabi --no-default-features
