name: ⚙️ no_std Compatibility

on:
  push:
    branches: [main, master, dev]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  nostd:
    runs-on: ubuntu-latest
    name: Check ${{ matrix.target }}
    strategy:
      matrix:
        target: [thumbv7m-none-eabi, aarch64-unknown-none]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: rustup target add ${{ matrix.target }}
      - run: cargo check --target ${{ matrix.target }} --no-default-features
