name: 🕒 Scheduled checks

on:
  push:
    branches: [main, master, dev]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  nightly:
    name: Test nightly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - run: RTSAN_ENABLE=1 cargo test --locked --all-features --all-targets

  update:
    name: Test updated
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@beta
      - run: cargo update
      - run: RTSAN_ENABLE=1  RUSTFLAGS="-D deprecated" cargo test --locked --all-features --all-targets
