name: 🧪 Cargo Tests

on:
  push:
    branches: [main, master, dev]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Run tests on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: RTSAN_ENABLE=1 cargo test --locked --all-features --all-targets --workspace

  test-from-source:
    name: Run tests with build from source on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: RTSAN_ENABLE=1 cargo test --locked --no-default-features --all-targets --workspace

  windows-test:
    name: Run tests on Windows (disabled RTSAN)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --locked --all-features --all-targets --workspace
